[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "1.0.0", features = ["ws", "rustls"] }
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"] }
eyre = "0.6"